---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: finance
          image: eranil2u/finance:v1
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: finance
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: finance
